# toolpath_planner.py
"""Generate robotic fabrication toolpaths from Rhino geometry."""

import math
from dataclasses import dataclass
from typing import List, Tuple


@dataclass
class ToolpathPoint:
    x: float
    y: float
    z: float
    rx: float = 0.0  # rotation X
    ry: float = 0.0  # rotation Y
    rz: float = 0.0  # rotation Z
    speed: float = 100.0  # mm/s
    command: str = "MOVE"


class ToolpathPlanner:
    """Generate robot toolpaths from design geometry."""
    
    def __init__(self, tool_radius: float = 6.0):
        self.tool_radius = tool_radius
        self.paths: List[List[ToolpathPoint]] = []
    
    def slice_layer(self, z_height: float, 
                     boundary: List[Tuple[float, float]],
                     infill_spacing: float = 5.0) -> List[ToolpathPoint]:
        """Generate a single print layer at given height."""
        points = []
        
        # Boundary contour
        for i, (x, y) in enumerate(boundary):
            points.append(ToolpathPoint(x, y, z_height, speed=80.0))
        
        # Connect back to start
        points.append(ToolpathPoint(
            boundary[0][0], boundary[0][1], z_height, speed=150.0
        ))
        
        # Infill (simple zigzag pattern)
        min_x = min(p[0] for p in boundary)
        max_x = max(p[0] for p in boundary)
        min_y = min(p[1] for p in boundary)
        max_y = max(p[1] for p in boundary)
        
        y = min_y + infill_spacing
        direction = 1
        while y < max_y:
            start_x = min_x if direction > 0 else max_x
            end_x = max_x if direction > 0 else min_x
            points.append(ToolpathPoint(start_x, y, z_height, speed=150.0, command="MOVE"))
            points.append(ToolpathPoint(end_x, y, z_height, speed=50.0, command="PRINT"))
            y += infill_spacing
            direction *= -1
        
        return points
    
    def export_gcode(self, path: str = "output.gcode"):
        """Export toolpath as G-code."""
        with open(path, "w") as f:
            f.write("; Generated by ROS2-Robotic-Architecture\n")
            f.write("G21 ; Set units to mm\n")
            f.write("G90 ; Absolute positioning\n\n")
            
            for i, layer in enumerate(self.paths):
                f.write(f"; Layer {i}\n")
                for pt in layer:
                    if pt.command == "MOVE":
                        f.write(f"G0 X{pt.x:.2f} Y{pt.y:.2f} Z{pt.z:.2f} F{pt.speed}\n")
                    elif pt.command == "PRINT":
                        f.write(f"G1 X{pt.x:.2f} Y{pt.y:.2f} Z{pt.z:.2f} F{pt.speed}\n")
        
        print(f"Exported {sum(len(p) for p in self.paths)} commands to {path}")


if __name__ == "__main__":
    planner = ToolpathPlanner()
    
    # Sample: print a 50x50mm square
    boundary = [(0, 0), (50, 0), (50, 50), (0, 50)]
    for z in range(1, 11):  # 10 layers
        layer = planner.slice_layer(z * 2.0, boundary)
        planner.paths.append(layer)
    
    planner.export_gcode("docs/sample_toolpath.gcode")
    print("Sample toolpath generated")
